#!/usr/bin/env python3

# Software License Agreement (BSD License)
#
# Copyright (c) 2012, Robotiq, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of Robotiq, Inc. nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Copyright (c) 2012, Robotiq, Inc.
# Revision $Id$

"""@package docstring
Command-line interface for receiving and interpreting the status of a 2F gripper.

This serves as an example for receiving messages from the 'Robotiq2FGripperRobotInput' topic using the 'Robotiq2FGripper_robot_input' msg type and interpreting the corresponding status of the 2F gripper.
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
from robotiq_2f_gripper_control.msg import Robotiq2FGripperInput  as inputMsg

def printStatus(status):
    """Print the status string generated by the statusInterpreter function."""

    print(statusInterpreter(status))

def Robotiq2FGripperStatusListener():
    """Initialize the node and subscribe to the Robotiq2FGripperRobotInput topic."""

    rclpy.init()

    node = Node('Robotiq2FGripperStatusListener')
    node.create_subscription(inputMsg, "Robotiq2FGripperRobotInput", printStatus, 1)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    node.destroy_node()
    rclpy.shutdown()

def statusInterpreter(status):
    """Generate a string according to the current value of the status variables."""

    output = '\n-----\n2F gripper status interpreter\n-----\n'

    #g_act
    output += 'g_act = ' + str(status.g_act) + ': '
    if(status.g_act == 0):
       output += 'Gripper reset\n'
    if(status.g_act == 1):
       output += 'Gripper activation\n'

    #g_gto
    output += 'g_gto = ' + str(status.g_gto) + ': '
    if(status.g_gto == 0):
        output += 'Standby (or performing activation/automatic release)\n'
    if(status.g_gto == 1):
        output += 'Go to Position Request\n'

    #g_sta
    output += 'g_sta = ' + str(status.g_sta) + ': '
    if(status.g_sta == 0):
        output += 'Gripper is in reset ( or automatic release ) state. see Fault Status if Gripper is activated\n'
    if(status.g_sta == 1):
        output += 'Activation in progress\n'
    if(status.g_sta == 2):
        output += 'Not used\n'
    if(status.g_sta == 3):
        output += 'Activation is completed\n'

    #g_obj
    output += 'g_obj = ' + str(status.g_obj) + ': '
    if(status.g_obj == 0):
        output += 'Fingers are in motion (only meaningful if g_gto = 1)\n'
    if(status.g_obj == 1):
        output += 'Fingers have stopped due to a contact while opening\n'
    if(status.g_obj == 2):
        output += 'Fingers have stopped due to a contact while closing \n'
    if(status.g_obj == 3):
        output += 'Fingers are at requested position\n'
 
    #g_flt
    output += 'g_flt = ' + str(status.g_flt) + ': '
    if(status.g_flt == 0x00):
        output += 'No Fault\n'
    if(status.g_flt == 0x05):
        output += 'Priority Fault: Action delayed, initialization must be completed prior to action\n'
    if(status.g_flt == 0x07):
        output += 'Priority Fault: The activation bit must be set prior to action\n'
    if(status.g_flt == 0x09):
        output += 'Minor Fault: The communication chip is not ready (may be booting)\n'
    if(status.g_flt == 0x0B):
        output += 'Minor Fault: Automatic release in progress\n'
    if(status.g_flt == 0x0E):
        output += 'Major Fault: Overcurrent protection triggered\n'
    if(status.g_flt == 0x0F):
        output += 'Major Fault: Automatic release completed\n'

    #g_pr
    output += 'g_pr = ' + str(status.g_pr) + ': '
    output += 'Echo of the requested position for the Gripper: ' + str(status.g_pr) + '/255\n'

    #g_po
    output += 'g_po = ' + str(status.g_po) + ': '
    output += 'Position of Fingers: ' + str(status.g_po) + '/255\n'

    #g_cu
    output += 'g_cu = ' + str(status.g_cu) + ': '
    output += 'Current of Fingers: ' + str(status.g_cu * 10) + ' mA\n'

    return output
    
if __name__ == '__main__':
    Robotiq2FGripperStatusListener()
